### PR TITLE
Alll features were developed and are ready to be reviewed

### PR DESCRIPTION
**Pull request by cochabambinoski**
Features were implemented according to https://www.theodinproject.com/courses/javascript/lessons/restaurant-page
The website is functional now.

### CODE REVIEW

**Comment by cochabambinoski** [comment]
Hello, I am not hiding anything, I am replacing all relevant elements, not touching divs or containers.
Using innerHTML I replace completely all. I can destroy with element.parentNode.removeChild(element), but I would have to copy and paste many several times the code.

**Comment by azdrenymeri** [comment]
## Hello @cochabambinoski :wave: 
- [ ] You haven't added `node_modules` on `.gitignore` so, as a result, all node modules are published on the remote branch.
- [ ]  You are missing a `<div id="content"></div>`(hardcoded in HTML) inside `index.html` that will be as a placeholder.
### Kindly implement these two changes and add it for another review.

**Comment by cochabambinoski** [comment]
Hello,

1.- I didn't add node_modules to gitignore because I want to try to make it run in GitHub Pages and that was a requirement according to the tutorial from Odin's Project page.
2.- I set the div in the code like:
  const element = document.createElement('div');
  element.classList.add('content');
  element.id = 'content';

And it looks like this:
image

**Comment by cochabambinoski** [comment]
sorry about that for .gitignore, now ignores node_modules. And now the index.html have the div id=content

**Pull request merged**
